import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Layout from "../components/layout";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const inter = Inter({ subsets: ["latin"] });
const queryClient = new QueryClient();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider client={queryClient}>
          <Layout>
            <main className="pt-16">{children}</main>
          </Layout>
        </QueryClientProvider>
      </body>
    </html>
  );
}
